apiVersion: v1
kind: Template
metadata:
  labels:
    type: image-scanning
  annotations:
    description: Jenkins Pipeline for Running OpenSCAP
    tags: scanning,security
  name: image-scanning-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
  labels:
    type: image-scanning
  spec:
    source:
          contextDir: image-scanning
          git:
            ref: master
            uri: https://github.com/bagnaram/openshift-image-signing-scanning.git
    type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: IMAGE_TO_SCAN
          value: "${IMAGE_TO_SCAN}"
        - name: SERVICE_ACCOUNT
          value: "${SERVICE_ACCOUNT}"
parameters:
- description: The Name for the Application.
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: scan-image
- description: Name of the Image to Scan.
  displayName: Image to Scan
  name: IMAGE_TO_SCAN
  required: true
  value: registry.access.redhat.com/rhel7/rhel:latest
- description: Name of the Service Account Used to Launch the Slave Pod.
  displayName: Slave Pod Service Account
  name: SERVICE_ACCOUNT
  value: jenkins
  required: true
